name: Docs

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps for docs
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f docs/requirements.txt ]; then
            pip install -r docs/requirements.txt
          else
            # fallback: чистый MkDocs (добавьте сюда плагины/темы при необходимости)
            pip install mkdocs
          fi

      - name: Detect mkdocs config and build
        run: |
          set -euo pipefail
          # Найдём конфиг в типичных местах
          if [ -f mkdocs.yml ]; then
            CFG="mkdocs.yml"; WD="."
          elif [ -f mkdocs.yaml ]; then
            CFG="mkdocs.yaml"; WD="."
          elif [ -f docs/mkdocs.yml ]; then
            CFG="mkdocs.yml"; WD="docs"
          elif [ -f docs/mkdocs.yaml ]; then
            CFG="mkdocs.yaml"; WD="docs"
          else
            echo "mkdocs.yml(yaml) не найден ни в корне, ни в docs/. Добавьте файл или укажите путь."
            exit 1
          fi

          echo "Using $WD/$CFG"
          cd "$WD"
          mkdocs --version
          mkdocs build --strict -f "$CFG"

      - name: Upload built site (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            site/**
