name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          echo "pytest" > requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create simple tests
        run: |
          mkdir -p tests
          echo "import os; assert os.path.exists('writer.py')" > tests/test_sample.py
      - name: Run tests
        run: pytest -q
