name: Docs

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Create minimal MkDocs project if missing
        run: |
          set -euo pipefail

          # нет ни одного конфига?
          if [ ! -f mkdocs.yml ] && [ ! -f mkdocs.yaml ] && \
             [ ! -f docs/mkdocs.yml ] && [ ! -f docs/mkdocs.yaml ]; then
            echo "No mkdocs config found. Creating a minimal one in repo root..."
            mkdir -p docs
            cat > mkdocs.yml <<YAML
site_name: "${GITHUB_REPOSITORY}"
nav:
  - Home: index.md
theme:
  name: mkdocs
YAML
            if [ ! -f docs/index.md ]; then
              cat > docs/index.md <<'MD'
# Welcome

Это стартовая страница MkDocs.
Отредактируйте `mkdocs.yml` и `docs/index.md` под свой проект.
MD
            fi
          fi

      - name: Detect config and build
        run: |
          set -euo pipefail

          # ищем конфиг в репозитории
          CFG_FILE="$(find . -type f \( -iname 'mkdocs.yml' -o -iname 'mkdocs.yaml' \) | head -n 1)"
          if [ -z "${CFG_FILE:-}" ]; then
            echo "❌ mkdocs.yml(yaml) не найден и не был создан."
            exit 1
          fi

          echo "✅ Using config: $CFG_FILE"
          WD="$(dirname "$CFG_FILE")"
          BASE_CFG="$(basename "$CFG_FILE")"

          cd "$WD"
          mkdocs --version
          mkdocs build --strict -f "$BASE_CFG"

      - name: Upload built site (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            **/site/**
