name: Docs

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs (and common extras)
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          # If you use a theme/plugins, add them here, e.g.:
          # pip install mkdocs-material mkdocs-minify-plugin mkdocs-markdownextradata-plugin

      - name: Show versions (optional, helps debugging)
        run: |
          python --version
          mkdocs --version

      - name: Build docs
        run: mkdocs build --strict
        # If mkdocs.yml isn't in repo root, point to it explicitly:
        # run: mkdocs build --strict -f docs/mkdocs.yml
